### ISSUE TITLE
Is there a reason why we pushed node_modules?

### ISSUE THREAD

**Issue by aloisdg** [d-edge/strip-markdown-html#7]
title :)

**Comment by Tarmil** [comment]
Github actions are loaded as a plain js file, not as a module, so in order to use modules such as remark, we need to have their source in the repo in some form. Committing node_modules is the easiest way to do that, some other actions do it (eg https://github.com/dawidd6/action-download-artifact).

But we could take the time to implement a build step, so that we just need to commit the resulting dist js. It might actually be easiest to use TypeScript.

**Comment by Tarmil** [comment]
Actually, ncc looks like the easy route. PR incoming
